## You should change each of the following fields
## to customize your blog

title: Stat 386 Blog
description: "Welcome to my Stat Blog! This is a blog I have for Data Science and Statistics!" 
author: Tyler Savage
author_description: "Statistics, Data Science student at Brigham Young University
                    Chief Data Analyst for Momentum Marketing" 

url: https://thatrealtyguy.github.io ## change this to https://yourusername.github.io
baseurl: /StatBlog ## change this to the name of your blog repository
header_image: /assets/img/headerimg.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github:  thatrealtyguy
    twitter: TyloRen99
    facebook: Tyler Savage
    email: thatrealtyguy@gmail.com
    linkedin: tyler-savage-1b998b138
    youtube: NotYourAverageSavage
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




